# Generated by Django 4.2.5 on 2023-09-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_visitor_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='photo',
        ),
        migrations.AddField(
            model_name='visitor',
            name='captured_photo',
            field=models.ImageField(blank=True, null=True, upload_to='captured_visitor_photos/'),
        ),
    ]
