# Generated by Django 4.2.5 on 2023-09-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_visitor_photo_visitor_captured_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='code',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
