# Generated by Django 4.2.5 on 2023-09-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_remove_qrcode_code_qrcode_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
