# Generated by Django 4.2.5 on 2023-10-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_qrcode_qr_code_qrcode_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='visitor',
        ),
    ]
