# Generated by Django 4.2.5 on 2023-10-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_remove_rating_post_delete_post_delete_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
