# Generated by Django 4.2.5 on 2023-10-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_delete_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('date_added',)},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='feedback',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 - star'), (2, '2 - stars'), (3, '3 - stars'), (4, '4 - stars'), (5, '5 - stars')]),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
