# Generated by Django 4.2.5 on 2023-10-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_feedback_options_alter_visitor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
