# Generated by Django 4.2.5 on 2023-10-04 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_alter_feedback_options_alter_visitor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
