# Generated by Django 4.2.5 on 2023-10-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_feedback_date_added_alter_visitor_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='visitor',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
