# Generated by Django 4.2.6 on 2023-11-10 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_feedback_options_alter_visitor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.visitor'),
        ),
    ]
