# Generated by Django 4.2.6 on 2023-11-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_visitor_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
