# Generated by Django 4.2.6 on 2023-12-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_alter_visitor_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.AddField(
            model_name='feedback',
            name='item_1',
            field=models.IntegerField(blank=True, choices=[(1, '1 - star'), (2, '2 - stars'), (3, '3 - stars'), (4, '4 - stars'), (5, '5 - stars')], null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='item_2',
            field=models.IntegerField(blank=True, choices=[(1, '1 - star'), (2, '2 - stars'), (3, '3 - stars'), (4, '4 - stars'), (5, '5 - stars')], null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='item_3',
            field=models.IntegerField(blank=True, choices=[(1, '1 - star'), (2, '2 - stars'), (3, '3 - stars'), (4, '4 - stars'), (5, '5 - stars')], null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='item_4',
            field=models.IntegerField(blank=True, choices=[(1, '1 - star'), (2, '2 - stars'), (3, '3 - stars'), (4, '4 - stars'), (5, '5 - stars')], null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='item_5',
            field=models.IntegerField(blank=True, choices=[(1, '1 - star'), (2, '2 - stars'), (3, '3 - stars'), (4, '4 - stars'), (5, '5 - stars')], null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='item_6',
            field=models.IntegerField(blank=True, choices=[(1, '1 - star'), (2, '2 - stars'), (3, '3 - stars'), (4, '4 - stars'), (5, '5 - stars')], null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='item_7',
            field=models.IntegerField(blank=True, choices=[(1, '1 - star'), (2, '2 - stars'), (3, '3 - stars'), (4, '4 - stars'), (5, '5 - stars')], null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='item_8',
            field=models.IntegerField(blank=True, choices=[(1, '1 - star'), (2, '2 - stars'), (3, '3 - stars'), (4, '4 - stars'), (5, '5 - stars')], null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='item_9',
            field=models.IntegerField(blank=True, choices=[(1, '1 - star'), (2, '2 - stars'), (3, '3 - stars'), (4, '4 - stars'), (5, '5 - stars')], null=True),
        ),
    ]
