# Generated by Django 4.2.6 on 2023-12-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_alter_feedback_item_1_alter_feedback_item_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_item_1', models.FloatField(default=0)),
                ('average_item_2', models.FloatField(default=0)),
                ('average_item_3', models.FloatField(default=0)),
                ('average_item_4', models.FloatField(default=0)),
                ('average_item_5', models.FloatField(default=0)),
                ('average_item_6', models.FloatField(default=0)),
                ('average_item_7', models.FloatField(default=0)),
                ('average_item_8', models.FloatField(default=0)),
                ('average_item_9', models.FloatField(default=0)),
            ],
        ),
    ]
