# Generated by Django 4.2.6 on 2023-12-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0025_delete_itemaverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField(unique=True)),
                ('average_rating', models.FloatField()),
            ],
        ),
    ]
