# Generated by Django 4.2.6 on 2023-12-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0027_alter_averagefeedback_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagefeedback',
            name='rating_description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
