# Generated by Django 4.2.6 on 2023-12-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0030_alter_averagefeedback_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagefeedback',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
