# Generated by Django 4.2.6 on 2023-12-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0033_alter_averagefeedback_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='department',
            field=models.CharField(choices=[('', 'Select a Department'), ('Engineering', 'Engineering'), ('Human Resources', 'Human Resources'), ('DPWH', 'DPWH')], max_length=20),
        ),
    ]
