# Generated by Django 4.2.6 on 2023-12-11 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0034_alter_visitor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='time_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visitor',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
